# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnormESGcpp <- function(N, M) {
    .Call('_ESGtoolkit_rnormESGcpp', PACKAGE = 'ESGtoolkit', N, M)
}

rOUESGcpp <- function(N, horizon, Delta, x0, theta, eps) {
    .Call('_ESGtoolkit_rOUESGcpp', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta, eps)
}

rOUESGcppexact <- function(N, horizon, Delta, x0, theta, eps) {
    .Call('_ESGtoolkit_rOUESGcppexact', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta, eps)
}

rCIRESGcpp <- function(N, horizon, Delta, x0, theta, eps) {
    .Call('_ESGtoolkit_rCIRESGcpp', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta, eps)
}

rCIRESGcppexact <- function(N, horizon, Delta, x0, theta, eps) {
    .Call('_ESGtoolkit_rCIRESGcppexact', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta, eps)
}

rGBMESGcpp <- function(N, horizon, Delta, x0, theta1, theta2, eps) {
    .Call('_ESGtoolkit_rGBMESGcpp', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta1, theta2, eps)
}

rGBMjumpsnormESGcpp <- function(N, horizon, Delta, x0, theta1, theta2, lambda, mu, sigma, eps) {
    .Call('_ESGtoolkit_rGBMjumpsnormESGcpp', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta1, theta2, lambda, mu, sigma, eps)
}

rGBMjumpskouESGcpp <- function(N, horizon, Delta, x0, theta1, theta2, lambda, eta_up, eta_down, p, eps) {
    .Call('_ESGtoolkit_rGBMjumpskouESGcpp', PACKAGE = 'ESGtoolkit', N, horizon, Delta, x0, theta1, theta2, lambda, eta_up, eta_down, p, eps)
}

TAGcorecpp <- function(sim, sj_down, sj_up, n, p) {
    .Call('_ESGtoolkit_TAGcorecpp', PACKAGE = 'ESGtoolkit', sim, sj_down, sj_up, n, p)
}

